# Generated by Django 4.1.3 on 2022-11-13 17:27

from django.db import migrations

import requests

POKEMON_LIMIT = 151
POKE_API_URL = 'https://pokeapi.co/api/v2/pokemon/{id}/'


# TODO: Right now I load each pokemon synchronously
# and it takes about 10-15 seconds to load 151 pokemon.
# I need to rewrite it asyncronously to make it faster.
def load_pokemons(apps, schema_editor):
    Pokemon = apps.get_model("pokemons", "Pokemon")
    pokemons = []

    for id in range(1, POKEMON_LIMIT):
        pokemon = requests.get(
            POKE_API_URL.format(id=id)
        ).json()
        pokemons.append(
            Pokemon(
                id=pokemon['id'],
                name=pokemon['name'],
                worth=pokemon['base_experience'],
                height=pokemon['height'],
                weight=pokemon['weight'],
                # TODO: Add more fields such as types, image
            ),
        )

    Pokemon.objects.bulk_create(pokemons)


def reverse(apps, schema_editor):
    Pokemon = apps.get_model("pokemons", "Pokemon")
    Pokemon.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_pokemons, reverse)
    ]
