# Generated by Django 4.1.3 on 2022-11-13 17:27

from django.db import migrations

import httpx
import asyncio

POKEMON_LIMIT = 151
POKE_API_URL = 'https://pokeapi.co/api/v2/pokemon/{id}/'

async def get_pokemon(client, model, id):
    body = (await client.get(
        POKE_API_URL.format(id=id)
    )).json()

    pokemon = model(
        id=body['id'],
        name=body['name'],
        worth=body['base_experience'],
        height=body['height'],
        weight=body['weight'],
        image=body['sprites']['other']['official-artwork']['front_default'],
        types=[pokemon_type['type']['name'] for pokemon_type in body['types']]
        # TODO: Add more fields such as types, image
    )
    return pokemon


def load_pokemons(apps, schema_editor):
    Pokemon = apps.get_model("pokemons", "Pokemon")

    async def get_pokemons():
        async with httpx.AsyncClient() as client:
            return await asyncio.gather(*[
                get_pokemon(client, Pokemon, id)
                for id in range(1, POKEMON_LIMIT)
            ])

    pokemons = asyncio.run(get_pokemons())
    Pokemon.objects.bulk_create(pokemons)


def reverse(apps, schema_editor):
    Pokemon = apps.get_model("pokemons", "Pokemon")
    Pokemon.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_pokemons, reverse)
    ]
